### ISSUE TITLE
traefik_ssl_email_address is required with web_secure_enabled: false

### ISSUE THREAD

**Issue by Zocker1999NET** [devture/com.devture.ansible.role.traefik#2]
**Describe the bug / feature request**
`devture_traefik_ssl_email_address` is required to be set even with `devture_traefik_config_entrypoint_web_secure_enabled: false`.

**Expected behavior**
Leaving `devture_traefik_ssl_email_address` empty if TLS termination is disabled.

That is even stated here in [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy):

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/ecde8a46f88dac66cdd61bb983a3c889f583f955/roles/custom/matrix-base/defaults/main.yml#L286

**Additional context**
I was opening this bug report in [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) but I decided to open it here because it seems that only this repo needs to be changed to fix this.

PS: This ([matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)) Ansible playbook saves me a ton of work. Thanks for maintaining & open sourcing it.

**Comment by spantaleev** [comment]
Fixed by [da90b6c](https://github.com/devture/com.devture.ansible.role.traefik/commit/da90b6cdbbb9374ca72c1b530867add2fd8f024e)
