### ISSUE TITLE
Additional entrypoints should not expose docker port when host bind port is empty

### ISSUE THREAD

**Issue by nielscil** [devture/com.devture.ansible.role.traefik#8]
An entrypoint provided to `devture_traefik_additional_entrypoints` has a option named `host_bind_port`. When this value is empty it still tries to expose the port in docker. Because the value is empty, a random port is chosen. I think it's an better idea to don't expose the port in that case.

**Comment by spantaleev** [comment]
Makes sense! `v2.10.1-2` contains the fix
